### ISSUE TITLE
BUG - Número de perguntas passando do limite

### ISSUE THREAD

**Issue by CaioMassola** [DevDaniloFerrari/Quizer#19]
* **Descrição: Ao inserir o número de perguntas através do teclado, o número passa do limite disponível.**

* O bug provavelmente acontece devido algum erro no **queryParam da quantidadePerguntas** que é perdido em alguma renderização.

<details>
<summary>Evidência</summary>

https://github.com/DevDaniloFerrari/Quizer/assets/47333514/fa7e594a-d780-433c-987e-f98d5df9140e

</details>

**Comment by DevDaniloFerrari** [comment]
Boa Caio, peguei esse bug aqui também durantes uns testes.
Pode pegar pra resolver. Vlw!!

**Comment by CaioMassola** [comment]
Salve man

Blzinha, vou ir de dale

@DevDaniloFerrari  só vou precisar de uma DOC para configurar o firebase com as variáveis do ENV, pode colocar no guia de contribuição pls

**Comment by DevDaniloFerrari** [comment]
@CaioMassola , enviei o arquivo .env.local no seu email. Estou fazendo algumas alterações aqui e ainda não sei como disponibilizar isso para todos pq tem dados sensíveis.

**Comment by CaioMassola** [comment]
Opa, aqui não chegou o email.

Sobre como fazer a disponibilização, poderia criar uma variável local mesmo no proprio ENV, se a variável for ambiente local, utilizaria as questões como estava vindo diretamente do codigo, e se for ambiente de produção poderia utilizar vindo do firebase, ai não precisaria passar a configuração do firebase para a galera.

**Comment by DevDaniloFerrari** [comment]
Fiz esse ajuste, pode testar ai!

**Comment by CaioMassola** [comment]
Salve @DevDaniloFerrari , blz?

finalizei o ajuste do BUG, só preciso testar vindo do firebase, consegue dar uma olhada?

**Comment by DevDaniloFerrari** [comment]
Vlw pela implementação!
