### ISSUE TITLE
Deixar o tempo de resposta configurável

### ISSUE THREAD

**Issue by DevDaniloFerrari** [DevDaniloFerrari/Quizer#2]
Na tela inicial deve-se colocar mais um input abaixo de **Quantidade de Perguntas**, que corresponderá ao tempo total para responder a pergunta.
![image](https://github.com/DevDaniloFerrari/Quizer/assets/40414119/8ab816e2-d0e8-4da5-98dc-e7150dd8eb65)

O valor do input será de no mínimo **10** e no máximo **60** e deve refletir em todas as perguntas

![image](https://github.com/DevDaniloFerrari/Quizer/assets/40414119/cd7b22d0-1717-42db-81c7-acd4ac37b007)

**Comment by CaioMassola** [comment]
Salve Danilo, blzinha? 

Gostaria de contribuir novamente com essa task.

**Comment by DevDaniloFerrari** [comment]
Opa @CaioMassola, beleza!
Pode seguir no desenvolvimento.

**Comment by CaioMassola** [comment]
Salve @DevDaniloFerrari blz? finalizei a task.

Fazendo está tarefa me deparei com um [BUG](https://github.com/DevDaniloFerrari/Quizer/issues/19) abri uma issue para isso, lá eu explico melhor.

E também criei uma [TASK](https://github.com/DevDaniloFerrari/Quizer/issues/20) para criar um formulário com tratativas de erros.

**Comment by DevDaniloFerrari** [comment]
Muito bom Caioo, vlw pela implementação.
Vou dar uma olhada nas Issues.
