### ISSUE TITLE
Implementar formulário para definir quantidade de perguntas e o tempo de resposta

### ISSUE THREAD

**Issue by CaioMassola** [DevDaniloFerrari/Quizer#20]
Descrição:  no campo de quantidade de perguntas é setado um limite de 1 a 30 perguntas, porém se o usuário colocar manualmente através do teclado um valor maior que 30, o código deixar passar o que pode ocasionar neste [BUG](https://github.com/DevDaniloFerrari/Quizer/issues/19), e se o valor for 0, o site não carrega mais.

 O mesmo vale para o campo de tempo de resposta que é entre 1 a 60s.

## Objetivo 

* Retirar a lógica de min e max dos inputs e fazer a validação através de um **formulário**
* Campo Quantidade de Perguntas  irá receber um valor entre 1 e 30;
* Campo Tempo de Resposta irá receber um valor entre 10 e 60;
* Se os valores não estiverem certos, informar o usuário com uma mensagem de erro;
* Se os valores não estiverem certos, desabilite o botão **Iniciar**

## Dica

* Utilizar a biblioteca [React Hook Form ](https://react-hook-form.com)

**Comment by CaioMassola** [comment]
Salve @DevDaniloFerrari ! de boas? vi que a tarefa do bug foi mergeada, testei aqui e funcionou legal ^^^

agora da para fazer essa task aqui do form, posso pegar?

**Comment by DevDaniloFerrari** [comment]
Opa, de boa! Pode seguir no desenvolvimento!
