### ISSUE TITLE
Colocar efeito sonoro ao acertar e errar pergunta

### ISSUE THREAD

**Issue by DevDaniloFerrari** [DevDaniloFerrari/Quizer#27]
Quando o usuário errar uma questão deve tocar um efeito sonoro de erro e ao acertar um efeito de acerto.

![image](https://github.com/DevDaniloFerrari/Quizer/assets/40414119/1534bfc0-985f-4632-80c8-162df92f0db8)

**Comment by CaioMassola** [comment]
Salve @DevDaniloFerrari, vou pegar essa aqui, blz?

**Comment by DevDaniloFerrari** [comment]
Opa, blz!

**Comment by CaioMassola** [comment]
Salve @DevDaniloFerrari blz? , finalizei a task aqui, tive que usar uma branch antiga para fazer, pois a versão da master está com esse erro.

 Acho que não deu nenhum conflito kkkk.

![image](https://github.com/DevDaniloFerrari/Quizer/assets/47333514/9691253f-ddd8-4972-8767-b9f971e6c5cb)

**Comment by DevDaniloFerrari** [comment]
Vlww @CaioMassola, feito o merge!
