### ISSUE TITLE
Implementar histórico da partida 

### ISSUE THREAD

**Issue by CaioMassola** [DevDaniloFerrari/Quizer#31]
* Na tela de resultado, seria interessante mostrar o histórico da partida, mostrando quais questões estavam corretas ou não.

* Implementar um drawer ou modal que será aberto ao clicar no botão "Histórico" nesta página.

![image](https://github.com/DevDaniloFerrari/Quizer/assets/47333514/06556257-4565-496b-ba02-6660a616a171)

**Comment by DevDaniloFerrari** [comment]
Boa ideia, Caio! Tem interesse de desenvolver essa parte?

**Comment by CaioMassola** [comment]
Salve @DevDaniloFerrari, tudo certo?

Criei essa task aqui, mas é só uma ideia. Se achar boa, eu pego e já faço.

**Comment by CaioMassola** [comment]
@DevDaniloFerrari boa, vou pegar ela e ir da daleee

**Comment by DevDaniloFerrari** [comment]
Beleza, deixei no seu nome, vlww!

**Comment by CaioMassola** [comment]
Salve @DevDaniloFerrari, blzinha?

Passando pra avisar que finalizei essa task!

**Comment by DevDaniloFerrari** [comment]
Opa @CaioMassola, bleza!!
Vlww, fiz o merge.
