### ISSUE TITLE
Melhor experiência de login

### ISSUE THREAD

**Issue by DevDaniloFerrari** [DevDaniloFerrari/Quizer#33]
Hoje, ao clicar no ícone do usuário é feito o login via Google automaticamente.
Esse ícone de usuário deve ser trocado por um botão escrito 'Login' que irá direcionar para a página de login.

Deve-se criar uma página de login, e colocar um botão para Login com Google (que já funciona atualmente).
Deve-se implementar a lógica para o usuário se cadastrar com email, senha e foto de perfil.
Deve-se implementar o login via email e senha.

![image](https://github.com/DevDaniloFerrari/Quizer/assets/40414119/4ce4e35c-e191-4902-96af-7fc88fd7a302)

A página de login deve ficar similar a este exemplo:
![image](https://github.com/DevDaniloFerrari/Quizer/assets/40414119/c7c95386-3933-41b1-a876-47ba5db2f233)
![image](https://github.com/DevDaniloFerrari/Quizer/assets/40414119/892bc3f8-c6f9-4658-a93f-f9b58e8404ff)

**Comment by CaioMassola** [comment]
Salve @DevDaniloFerrari, blzinha?

Posso pegar essa ai?

**Comment by DevDaniloFerrari** [comment]
Opa, pode sim @CaioMassola.
Só esta um pouco diferente pq eu implementei o menu lateral.
Mas a ideia é a mesma.

**Comment by CaioMassola** [comment]
Salve @DevDaniloFerrari, blz? finalizei a tela de login e cadastro, só falta implementar a logica do firebase agora para salvar o usuário.

E nessa task tmb, alterei um pouco do drawer lateral o que ocasionou na perca do responsivo que você implementou, vou abrir uma task para corrigir.

criei a task: https://github.com/DevDaniloFerrari/Quizer/issues/45

**Comment by DevDaniloFerrari** [comment]
Beleza, amanhã vou pegar pra implementar e testar com firebase!

**Comment by DevDaniloFerrari** [comment]
Implementei o cadastro e login com email e senha via firebase :)
