### ISSUE TITLE
Implementar menu lateral

### ISSUE THREAD

**Issue by DevDaniloFerrari** [DevDaniloFerrari/Quizer#34]
Implementar menu lateral e remover botões da home.

**Comment by CaioMassola** [comment]
Salve @DevDaniloFerrari, blz?

Na tarefa do histórico, eu criei um componente Drawer Genérico, ai da para usar ele passando um **children**

**Comment by DevDaniloFerrari** [comment]
Beleza @CaioMassola, acabei de implementar o menu lateral, depois vou adaptar pra tela de resultado final tbm.
vlww!
