### ISSUE TITLE
Melhorar o botão de baixar resultado

### ISSUE THREAD

**Issue by DevDaniloFerrari** [DevDaniloFerrari/Quizer#35]
Ao baixar o resultado e layout está um pouco estranho e deve-se remover os botões 'Tentar Novamente' e 'Baixar Resultado' da imagem.

![image](https://github.com/DevDaniloFerrari/Quizer/assets/40414119/4126c34f-1c7f-4149-823f-9c218197e0ef)

**Comment by CaioMassola** [comment]
@DevDaniloFerrari, vou pegar pra arrumar

**Comment by DevDaniloFerrari** [comment]
Feito o merge, vlw!
