### ISSUE TITLE
Verificar questões com duas alternativas iguais.

### ISSUE THREAD

**Issue by CaioMassola** [DevDaniloFerrari/Quizer#37]
Acredito que é só olhar na base de dados quais tem alternativas iguais e mudar.

![image](https://github.com/DevDaniloFerrari/Quizer/assets/47333514/5056c4ab-8799-4486-8474-4b3ff0a58b8f)

**Comment by DevDaniloFerrari** [comment]
Vlw pelo aviso, realmente tem alguns no banco que estão errado por conta dos testes do gerador de perguntas.
Arrumei esse mas acho que tem outros, se tiver me manda que eu ajusto tbm.

**Comment by CaioMassola** [comment]
Salve, peguei mais algumas iguais:

![image](https://github.com/DevDaniloFerrari/Quizer/assets/47333514/f989ad1e-5959-4432-8590-78b5b3030168)
![image](https://github.com/DevDaniloFerrari/Quizer/assets/47333514/a05c6b05-b370-4dc7-8f91-b1b05bd4f11a)
![image](https://github.com/DevDaniloFerrari/Quizer/assets/47333514/39ac9340-3ef4-473c-8b20-68fc4e975e18)
![image](https://github.com/DevDaniloFerrari/Quizer/assets/47333514/9e0b4512-de40-4ed8-b5fe-9bdcc2d824dd)
![image](https://github.com/DevDaniloFerrari/Quizer/assets/47333514/26449edb-bb1f-49fa-9717-b7ef8bfd82d9)
![image](https://github.com/DevDaniloFerrari/Quizer/assets/47333514/44f01f0b-fe06-43cc-981b-8c4c142b38be)
![image](https://github.com/DevDaniloFerrari/Quizer/assets/47333514/12fa5249-c35d-40eb-a643-3b557c8c13d9)
![image](https://github.com/DevDaniloFerrari/Quizer/assets/47333514/7bfa4924-fd5c-4747-a166-27194790eba7)
![image](https://github.com/DevDaniloFerrari/Quizer/assets/47333514/b47aa3e4-3e92-4f67-a844-407e0efabe3a)

**Comment by DevDaniloFerrari** [comment]
Boaa, estava precisando fazer isso faz tempo kkkk.
Agora ajustei todos, vlw!
