### ISSUE TITLE
Adiconar margem no avatar

### ISSUE THREAD

**Issue by DevDaniloFerrari** [DevDaniloFerrari/Quizer#39]
Adicionar margin bottom no avatar para desgrudar do menu item.

![image](https://github.com/DevDaniloFerrari/Quizer/assets/40414119/a08043b8-0b60-4b89-9ca0-3a47010a7a68)

**Comment by DevEsterCarvalho** [comment]
Oii, posso pegar esta para fazer?

**Comment by DevDaniloFerrari** [comment]
Olá, sim, pode seguir no desenvolvimento :)

**Comment by DevDaniloFerrari** [comment]
Já fiz o merge dessa alteração, obrigado @DevEsterCarvalho!
