### ISSUE TITLE
Novo Estilo para Scroll

### ISSUE THREAD

**Issue by CaioMassola** [DevDaniloFerrari/Quizer#42]
* Implementar um estilo personalizado para o scroll.

* Hoje, ele usa o padrão dos navegadores, porém é bem feinho kkkkk
* Então seria legal ter um scroll todo estilizado.

![image](https://github.com/DevDaniloFerrari/Quizer/assets/47333514/7b9a52e4-5d7c-409a-820b-55d79fc15454)

**Comment by CaioMassola** [comment]
@DevDaniloFerrari, vou pegar essa task aqui, blz?

**Comment by DevDaniloFerrari** [comment]
blz!

**Comment by DevDaniloFerrari** [comment]
@CaioMassola 
Alterei bastante coisa na página de resultado, pra conseguir implementar a parte final do modo competição.
Ainda preciso dar uma boa refatorada kkk, então talvez de conflito com essa tarefa.

**Comment by CaioMassola** [comment]
Opa, blz! mas acho que vou mexer só no css da pagina!

**Comment by DevDaniloFerrari** [comment]
Feito o merge, vlw!!
