### ISSUE TITLE
Criar design responsivo para menu lateral.

### ISSUE THREAD

**Issue by CaioMassola** [DevDaniloFerrari/Quizer#45]
* Criar um design responsivo para o menu lateral em telas menores.

* Algo semelhante a isso:
![image](https://github.com/DevDaniloFerrari/Quizer/assets/47333514/a5a0e91d-64ec-4acf-8752-aa3f922900c8)

**Comment by DevDaniloFerrari** [comment]
Já refiz o design, agr ficou show!

**Comment by CaioMassola** [comment]
Nice, ficou daora demais ^^
