### ISSUE TITLE
Implementar botão de voltar

### ISSUE THREAD

**Issue by DevDaniloFerrari** [DevDaniloFerrari/Quizer#5]
Na tela de perguntas deve-se implementar um botão no canto superior esquerdo que, ao clicar, irá direcionar o usuário para a tela inicial.

O botão deve ficar nessa tela
![image](https://github.com/DevDaniloFerrari/Quizer/assets/40414119/34c68b72-7675-4407-8097-e56a20b66aec)

E, ao clicar, voltar para essa tela
![image](https://github.com/DevDaniloFerrari/Quizer/assets/40414119/7137e69e-0805-4257-b3cb-3de1fc3e9072)

**Comment by CaioMassola** [comment]
Salve @DevDaniloFerrari, blz? gostaria de continuar contribuindo, ai queria pegar essa task e tmb já fazer essa outra [task](https://github.com/DevDaniloFerrari/Quizer/issues/3), pois é a mesma cosia, ai só editaria a descrição dessa tarefa para criar os dois botões

**Comment by DevDaniloFerrari** [comment]
Beleza @CaioMassola, pode seguir no desenvolvimento.
