### ISSUE TITLE
Indicar o total de perguntas respondidas e quantas restam

### ISSUE THREAD

**Issue by DevDaniloFerrari** [DevDaniloFerrari/Quizer#6]
Quando o usuário estiver respondendo as perguntas, deve-se mostrar o total que ele já respondeu e quantas ainda restam.

Essas informações devem ficar em algum lugar dessa tela
![image](https://github.com/DevDaniloFerrari/Quizer/assets/40414119/f8b19434-dd59-410e-ab4c-98d5d8579d26)

Seja criativo :smile:

**Comment by BeaGoddess** [comment]
Olá! Gostava de contribuir neste projeto, principalmente nesta issue 😄

**Comment by DevDaniloFerrari** [comment]
Olá @BeaGoddess, obrigado pelo interesse.
Pode seguir com o desenvolvimento.
