### ISSUE TITLE
Corrigir warning no build

### ISSUE THREAD

**Issue by DevDaniloFerrari** [DevDaniloFerrari/Quizer#7]
Está aparecendo um warning quando rodamos o comando `npm run build`

![image](https://github.com/DevDaniloFerrari/Quizer/assets/40414119/c1e9e526-0e5d-48eb-a71b-9d8b18cfe7ad)

Deve-se fazer as alterações necessárias para corrigir esse warning.

**Comment by Gismii** [comment]
Olá, DevDanilo,

Meu nome é Gismi,  voltei estudar o React com a intenção de focar fortemente nessa tecnologia ao longo deste ano.

Estou interessado em contribuir para o projeto, pois percebo que é uma iniciativa recente. Tenho notado que há um limite de issues a ser resolvida por usuário correto? Mas estou disposto a ajudar em qualquer aspecto que possa ser útil. Gostaria de saber se há alguma issue específica em que eu possa colaborar, começando por essa.

Achei top o projeto,  além de querer ajudar o mesmo será importante nos meus estudos em Nextjs e React.

**Comment by DevDaniloFerrari** [comment]
Olá Gismi, fico feliz pelo interesse.
Coloquei essa Issue no seu nome. Pode seguir no desenvolvimento.
Divulguei o projeto hoje, e estou acompanhando para ver qual vai ser o nível de adesão. Se tivermos poucos interessados, sinta-se a vontade para solicitar novas Issues.

**Comment by Gismii** [comment]
> Olá Gismi, fico feliz pelo interesse. Coloquei essa Issue no seu nome. Pode seguir no desenvolvimento. Divulguei o projeto hoje, e estou acompanhando para ver qual vai ser o nível de adesão. Se tivermos poucos interessados, sinta-se a vontade para solicitar novas Issues.

Otimo, agradeço. Sem querer dei unsubscribe nessa tarefa  rsrs se quiser pode inserir meu nome novamente, breve irei dar um fork..
