### ISSUE TITLE
Trocar o favicon

### ISSUE THREAD

**Issue by DevDaniloFerrari** [DevDaniloFerrari/Quizer#8]
Remover esse favicon
![image](https://github.com/DevDaniloFerrari/Quizer/assets/40414119/36dfceaf-cdcb-49fb-8b46-4df87f2efd3f)
e colocar um que seja mais relacionado a um Quiz.

**Comment by Laertebomfim** [comment]
Olá, tudo bem? Eu gostei muito da proposta do seu repositório e gostaria de colaborar para que eu possa aprender com o seu código. No entanto, logo depois que eu criei um fork e tentei rodar a aplicação, obtive esse erro:
```
FirebaseError: Firebase: Error (auth/invalid-api-key).
```
Para que eu possa realizar testes e possíveis alterações, eu preciso criar uma conta no Firebase?

**Comment by DevDaniloFerrari** [comment]
Olá @Laertebomfim, ainda estou vendo uma maneira de usar o emulador do firebase para resolver esse problema.
@CaioMassola, como vc está fazendo para desenvolver e não cair nesse problema?

**Comment by CaioMassola** [comment]
Opa, para ajustar esse problema, eu comentei os arquivos que chamam o AuthProvider, ele fica lá no layout.jsx

**Comment by DevDaniloFerrari** [comment]
Hmm saquei, é uma alternativa @Laertebomfim, pode tentar fazer isso.
Mas já estou implementando algo pra não precisar dessa gambiarra kkk.

**Comment by DevDaniloFerrari** [comment]
@Laertebomfim e @CaioMassola acabei de subir uma correção.
Foi simples mas resolveu o problema, podem testar :)
![image](https://github.com/DevDaniloFerrari/Quizer/assets/40414119/8df687ef-9da8-403f-881e-ab8b62557229)

**Comment by CaioMassola** [comment]
Salve! aqui deu bom!

**Comment by Laertebomfim** [comment]
Olá @DevDaniloFerrari. Para resolver esse problema, eu comentava todo o arquivo 
```
firebase.js
```

**Comment by CaioMassola** [comment]
@Laertebomfim precisa fazer isso mais não, só sincronizar o fork e dar um git pull

**Comment by Laertebomfim** [comment]
Funcionou para mim, @CaioMassola. Obrigado, @DevDaniloFerrari

**Comment by Laertebomfim** [comment]
Oi @DevDaniloFerrari, posso fazer essa aqui ?

**Comment by DevDaniloFerrari** [comment]
Olá @Laertebomfim, sim, já está em sue nome, pode seguir no desenvolvimento :)

**Comment by Laertebomfim** [comment]
Qual seria a imagem desejada ?

**Comment by DevDaniloFerrari** [comment]
Acredito que um ícone de interrogação já ficaria legal.

**Comment by DevDaniloFerrari** [comment]
Acabei de fazer o merge dessa issue @Laertebomfim, obrigado pela contribuição. 
Se puder, favorite o repositório:
![image](https://github.com/DevDaniloFerrari/Quizer/assets/40414119/4e752dd7-7ca3-4a7d-924f-cd92ae668eb3)
e ajude na divulgação para continuarmos evoluindo.
Sinta-se à vontade caso queira pegar outra issue também.
