### ISSUE TITLE
Implementar botão de download de resultado

### ISSUE THREAD

**Issue by DevDaniloFerrari** [DevDaniloFerrari/Quizer#9]
Na tela de resultado final, deve-se implementar um botão que irá baixar uma imagem em .jpg do resultado final.

![image](https://github.com/DevDaniloFerrari/Quizer/assets/40414119/a0e208a8-81a4-4193-9b76-2a9f3bb58a2e)

A imagem deve refletir exatamente a mesma disposição dos componentes. Para isso podemos utilizar, por exemplo, o pacote [html2canvas](https://www.npmjs.com/package/html2canvas).

**Comment by CaioMassola** [comment]
Salve Danilo, tudo na paz?

Gostaria de pegar essa task para ajudar.

**Comment by DevDaniloFerrari** [comment]
Fala Caio, quanto tempo!
Tudo certo e com você?

Manda bala!

**Comment by CaioMassola** [comment]
Finalizei a implementação! 

A iniciativa foi bem daora e vou continuar acompanhando ^^

**Comment by DevDaniloFerrari** [comment]
Boa Caio, vlww! Abre o PR que eu já aprovo aqui.

**Comment by CaioMassola** [comment]
opa, feito ^^
